name: plum_tiger
description: "An Investor Relations Consultancy Firm"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Automatically upgrade your package running `flutter pub upgrade --major-versions`. 
# Manualy updated by changing the version numbers, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.0.0
  image_picker: ^1.1.2
  network_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/Icon.png

  android_12:
    color: "#FFFFFF"
    image: assets/icons/Icon.png

  web: true

  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  #  - family: Roboto
  #   fonts:
  #      - asset: assets/fonts/Roboto-Regular.ttf
  #      - asset: assets/fonts/Roboto-Bold.ttf
  #        weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
